### PR TITLE
Update logo

### LINKED ISSUE #126: New Logo
As a follow-up to #121, we should update the logo.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #126 

Based on @wolfv sketches, thanks Wolf!

### CODE REVIEW

**Comment by jtpio** [comment]
### Readme

image

### About

image

image

**Comment by wolfv** [comment]
In the readme it might look slighly better when centered?

Maybe something like `` works in github markdown

**Comment by jtpio** [comment]
With the inline version and the [miami nights theme](https://github.com/timkpaine/jupyterlab_miami_nights):

image

**Comment by jtpio** [comment]
### Toolbar icon

image

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-change-the-logo-of-jupyterlab-on-top-right-corner/12239/2

**Pull request merged**
